# Don't change this! Version used to track needed updates.
version = 0
enableParticleCulling = true
particleRenderDistance = 5
cullParticlesInUnloadedChunks = true
glowingLavaDrops = true
fluidDropsEvaporate = true
fluidDropsEvaporationVolume = 0.25
dropLandInFluidSplashes = true
dropLandSounds = true
lavaSparkSmoke = true
sparksScale = 1.0
poppingHearts = true
poppingBubbles = true
poppingBubblesVolume = 0.2
glowingEnchantmentParticles = true
translucentEnchantmentParticles = true
forceWhiteEnchantmentParticles = true
mobSkullShaders = true
fireHeight = -0.15
nightVisionFading = true
nightVisionFadingTime = 100
enableEasterEggs = true