version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
farmersdelight = true
spelunkery = true
doapi = true
spudaciousshops = false
storagedrawers = true
templates = false
brewery = true
friendsandfoes = true
natures_spirit = false
twigs = true
copycats = false
stonezone = true
comforts = true
duckling = true
sootychimneys = true
sleep_tight = true
railways = false
phantasm = true
herbalbrews = true
handcrafted = true
ftbquests = true
customportalapi = true
ironchests = true
placeables_mod_fabric = true
supplementaries = true
grassoverhaul = true
deeperdarker = true
homestead = true
beachparty = true
create = false
biomeswevegone = true
minecraft = true
animal_feeding_trough = true
uncraftingtable76 = true
natures_delight = false
spawn = true
wetlands = true
wirelessredstone = true
toms_storage = true
expandeddelight = true
candlelight = true
simple_copper_pipes = true
ribbits = true
oceansdelight = true
variantcraftingtables = true
betterend = true
libraryferret = true
dustydecorations = true
justoutdoorstuffs = true
mysticsbiomes = true
diagonalwalls = false
mythicupgrades = true
ends_delight = true
lamps = true
enhancedcelestials = true
mcwpaths = true
nethersdelight = true
palegardenbackport = true
things = true
milk = true
amendments = true
diagonalfences = false
heracles = true
advancednetherite = true
sophisticatedbackpacks = true
redeco = true
cratedelight = true
hexalia = true
suppsquared = true
bedspreads = true
chipped = true
clutter = true
sawmill = true
lantern-mod = true
farm_and_charm = true
luphieclutteredmod = false
trashcans = true
wildernature = true
bronze = true
alcocraftplus = false
lootr = true
createdeco = false
mdm = true
regions_unexplored = true
blahaj = true
perfectplushies = true
fetzisasiandeco = true
beautify = true
dried_ghast = true
diagonalwindows = false
umbrellas = true
villagersplus = true
questsadditions = true
vinery = true
gofish = true
meadow = true
hearth_and_home = true
