[General]
	#Invert the behavior of the shift key for extracting items
	invertShift = false
	#Invert left and right click action on drawers
	invertClick = false

[Integration]
	#Enable extended data display in WAILA if present
	enableWaila = true
	#Enable extended data display in The One Probe if present
	enableTheOneProbe = true

[Render]
	#Distance in blocks before item labels stop rendering
	labelRenderDistance = 20.0
	#Distance in blocks before quantity numbers stop rendering
	quantityRenderDistance = 10.0
	#Distance in blocks before quantity numbers begin to fade out
	quantityFadeDistance = 20.0
